# Analyzing Relationships with Machine Learning

By: Oscar Ko

This notebook is created to analyze this dataset on relationships from Stanford:

https://data.stanford.edu/hcmst2017

---
---

# Imports and Data

In [2]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')


imported_data = pd.read_stata("data/HCMST 2017 fresh sample for public sharing draft v1.1.dta")

imported_data.shape

(3510, 285)

In [3]:
imported_data.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3510 entries, 0 to 3509
Data columns (total 285 columns):
 #    Column                            Non-Null Count  Dtype
---   ------                            --------------  -----
 0    CaseID                            3510 non-null   int16
 1    CASEID_NEW                        3510 non-null   int32
 2    qflag                             3510 non-null   category
 3    weight1                           2994 non-null   float64
 4    weight1_freqwt                    2994 non-null   float32
 5    weight2                           551 non-null    float64
 6    weight1a                          3110 non-null   float64
 7    weight1a_freqwt                   3110 non-null   float32
 8    weight_combo                      3510 non-null   float32
 9    weight_combo_freqwt               3510 non-null   float32
 10   duration                          3510 non-null   int16
 11   speed_flag                        3510 non-null   category
 12   consent                           3510 non-null   category
 13   xlgb                              3510 non-null   category
 14   S1                                3510 non-null   category
 15   S2                                1425 non-null   category
 16   S3                                648 non-null    category
 17   DOV_Branch                        3403 non-null   category
 18   Q3_Refused                        9 non-null      category
 19   Q4                                2856 non-null   category
 20   Q5                                468 non-null    category
 21   Q6A                               2856 non-null   category
 22   Q6B                               2856 non-null   category
 23   Q9                                2856 non-null   category
 24   Q10                               2856 non-null   category
 25   Q11                               2856 non-null   category
 26   Q12                               2856 non-null   category
 27   Q14                               2856 non-null   category
 28   Q15A7                             2856 non-null   category
 29   Q16                               2836 non-null   float64
 30   Q16_Refused                       20 non-null     category
 31   Q17A                              2079 non-null   category
 32   Q17B                              777 non-null    category
 33   Q17C                              1442 non-null   category
 34   Q17D                              1414 non-null   category
 35   Q19                               2856 non-null   category
 36   Q20                               465 non-null    category
 37   Q21A_Year                         2856 non-null   category
 38   Q21A_Month                        2856 non-null   category
 39   Q21B_Year                         2856 non-null   category
 40   Q21B_Month                        2856 non-null   category
 41   Q21C_Year                         2494 non-null   category
 42   Q21C_Month                        2494 non-null   category
 43   Q21D_Year                         2079 non-null   category
 44   Q21D_Month                        2079 non-null   category
 45   w6_identity                       2856 non-null   category
 46   w6_outness                        425 non-null    category
 47   w6_outness_timing                 371 non-null    category
 48   Q23                               2856 non-null   category
 49   Q24_Refused                       70 non-null     category
 50   Q25                               2856 non-null   category
 51   Q26                               1597 non-null   category
 52   Q27                               2856 non-null   category
 53   Q28                               2856 non-null   category
 54   w6_friend_connect_1               2856 non-null   category
 55   w6_friend_connect_2               2856 non-null   category
 56   w6_friend_connect_3               2856 non-null   category
 57   w6_friend_connect_4               2856 non-null   category
 58   w6_friend_connect_Refused         2856 non-null   category
 59   Q32                               2856 non-null   category
 60   Q34                               2856 non-null   category
 61   Q35_Refused                       220 non-null    category
 62   w6_sex_frequency                  2856 non-null   category
 63   w6_otherdate                      2856 non-null   category
 64   w6_how_many                       225 non-null    category
 65   w6_how_meet_Refused               12 non-null     category
 66   w6_otherdate_app                  224 non-null    category
 67   w6_how_many_app                   58 non-null     category
 68   Past_Partner_Q1                   538 non-null    category
 69   w6_relationship_end_nonmar        406 non-null    category
 70   w6_breakup_nonmar                 370 non-null    category
 71   w6_relationship_end_mar           132 non-null    category
 72   w6_who_breakup                    68 non-null     category
 73   Q5_2                              141 non-null    category
 74   Q6A_2                             538 non-null    category
 75   Q9B_2                             538 non-null    category
 76   Q10_2                             538 non-null    category
 77   Q11_2                             538 non-null    category
 78   Q12_2                             538 non-null    category
 79   Q14_2                             538 non-null    category
 80   Q15A7_2_1                         538 non-null    category
 81   Q16_2                             538 non-null    category
 82   Q16_2_Codes                       7 non-null      category
 83   Q17B_2                            538 non-null    category
 84   Q17C_2                            280 non-null    category
 85   Q17D_2                            258 non-null    category
 86   Q20_2                             538 non-null    category
 87   Q21A_2_Year                       538 non-null    category
 88   Q21A_2_Month                      538 non-null    category
 89   Q21B_2_Year                       538 non-null    category
 90   Q21B_2_Month                      538 non-null    category
 91   Q21C_2_Year                       234 non-null    category
 92   Q21C_2_Month                      234 non-null    category
 93   Q21D_2_Year                       132 non-null    category
 94   Q21D_2_Month                      132 non-null    category
 95   Q21E_2_Year                       438 non-null    category
 96   Q21E_2_Month                      438 non-null    category
 97   Q21F_2_start_range                525 non-null    category
 98   Q21F_2_Year                       100 non-null    category
 99   Q21F_2_Month                      100 non-null    category
 100  w6_identity_2                     538 non-null    category
 101  w6_outness_2                      125 non-null    category
 102  w6_outness_timing_2               108 non-null    category
 103  Q23_2                             538 non-null    category
 104  Q25_2                             538 non-null    category
 105  Q26_2                             202 non-null    category
 106  Q27_2                             538 non-null    category
 107  Q28_2                             538 non-null    category
 108  w6_friend_connect_2_1             538 non-null    category
 109  w6_friend_connect_2_2             538 non-null    category
 110  w6_friend_connect_2_3             538 non-null    category
 111  w6_friend_connect_2_4             538 non-null    category
 112  w6_friend_connect_2_Refused       538 non-null    category
 113  Q32_2                             538 non-null    category
 114  w6_otherdate_2                    538 non-null    category
 115  w6_how_many_2                     104 non-null    category
 116  w6_otherdate_app_2                101 non-null    category
 117  w6_how_many_app_2                 40 non-null     category
 118  partyid7                          3394 non-null   category
 119  PERSNET_hom                       3510 non-null   category
 120  ppc10017                          3510 non-null   category
 121  ppc21310                          3510 non-null   category
 122  ppp20071                          3394 non-null   category
 123  ppp20072                          3394 non-null   category
 124  ppage                             3510 non-null   category
 125  ppagecat                          3510 non-null   category
 126  ppagect4                          3510 non-null   category
 127  ppeduc                            3510 non-null   category
 128  ppeducat                          3510 non-null   category
 129  ppethm                            3510 non-null   category
 130  ppgender                          3510 non-null   category
 131  pphhhead                          3510 non-null   category
 132  pphhsize                          3510 non-null   category
 133  pphouse                           3510 non-null   category
 134  ppincimp                          3510 non-null   category
 135  ppmarit                           3510 non-null   category
 136  ppmsacat                          3510 non-null   category
 137  PPREG4                            3510 non-null   category
 138  ppreg9                            3510 non-null   category
 139  pprent                            3510 non-null   category
 140  PPT01                             3510 non-null   category
 141  PPT25                             3510 non-null   category
 142  PPT612                            3510 non-null   category
 143  PPT1317                           3510 non-null   category
 144  PPT18OV                           3510 non-null   category
 145  ppwork                            3510 non-null   category
 146  Race_1                            3510 non-null   category
 147  Race_2                            3510 non-null   category
 148  Race_3                            3510 non-null   category
 149  Race_4                            3510 non-null   category
 150  Race_5                            3510 non-null   category
 151  Race_6                            3510 non-null   category
 152  race1                             3510 non-null   category
 153  race2                             3510 non-null   category
 154  race3                             3510 non-null   category
 155  race4                             3510 non-null   category
 156  race5                             3510 non-null   category
 157  race6                             3510 non-null   category
 158  race7                             3510 non-null   category
 159  race8                             3510 non-null   category
 160  race9                             3510 non-null   category
 161  race10                            3510 non-null   category
 162  race11                            3510 non-null   category
 163  race12                            3510 non-null   category
 164  race13                            3510 non-null   category
 165  race14                            3510 non-null   category
 166  race15                            3510 non-null   category
 167  w6_took_the_survey                3510 non-null   category
 168  w6_prior_identity_lgb             3394 non-null   category
 169  w6_same_sex_couple                3394 non-null   category
 170  w6_same_sex_couple_gender         3394 non-null   category
 171  w6_q4                             3394 non-null   category
 172  w6_q5                             609 non-null    category
 173  w6_q6a                            3394 non-null   category
 174  w6_q6b                            3394 non-null   category
 175  w6_q9                             3374 non-null   float64
 176  w6_q10                            3394 non-null   category
 177  w6_q11                            3394 non-null   category
 178  w6_q12                            3394 non-null   category
 179  w6_q14                            3394 non-null   category
 180  w6_q15a1_truncated                3394 non-null   category
 181  w6_q15a4_truncated                3394 non-null   category
 182  w6_q15a7                          3394 non-null   category
 183  w6_q16                            3367 non-null   float64
 184  w6_q17                            3385 non-null   float64
 185  w6_attraction                     3381 non-null   category
 186  w6_q19                            2856 non-null   category
 187  w6_q20                            1003 non-null   category
 188  w6_q21a_year                      3341 non-null   float64
 189  w6_q21a_month                     3350 non-null   category
 190  w6_q21a_month_flag                3341 non-null   category
 191  w6_q21b_year                      3276 non-null   float64
 192  w6_q21b_month                     3301 non-null   category
 193  w6_q21b_month_flag                3301 non-null   float64
 194  w6_q21c_year                      2630 non-null   float64
 195  w6_q21c_month                     2649 non-null   category
 196  w6_q21c_month_flag                80 non-null     float64
 197  w6_q21d_year                      2169 non-null   float64
 198  w6_q21d_month                     2123 non-null   category
 199  w6_q21e_year                      410 non-null    float64
 200  w6_q21e_month                     395 non-null    category
 201  w6_q21f_year                      96 non-null     float64
 202  w6_q21f_month                     90 non-null     category
 203  w6_identity_all                   3394 non-null   category
 204  w6_outness_all                    550 non-null    category
 205  w6_outness_timing_all             476 non-null    float64
 206  w6_q23                            3394 non-null   category
 207  w6_q24_length                     3394 non-null   float32
 208  w6_q25                            3394 non-null   category
 209  w6_q26                            1799 non-null   float64
 210  w6_q27                            3394 non-null   category
 211  w6_q28                            3394 non-null   category
 212  w6_friend_connect_1_all           3394 non-null   category
 213  w6_friend_connect_2_all           3394 non-null   category
 214  w6_friend_connect_3_all           3394 non-null   category
 215  w6_friend_connect_4_all           3394 non-null   category
 216  w6_q32                            3394 non-null   category
 217  w6_q34                            2856 non-null   category
 218  w6_otherdate_all                  3394 non-null   category
 219  w6_how_many_all                   329 non-null    category
 220  w6_otherdate_app_all              325 non-null    category
 221  w6_how_many_app_all               98 non-null     category
 222  w6_number_people_met              3359 non-null   float32
 223  w6_otherdate_dichotomous          3363 non-null   category
 224  w6_married                        3394 non-null   category
 225  relate_duration_at_w6_years       2765 non-null   float32
 226  w6_number_people_met_app          323 non-null    float32
 227  weight_combo_v2                   3510 non-null   float32
 228  partnership_status                3510 non-null   category
 229  female                            3510 non-null   int8
 230  year_fraction_met                 3341 non-null   float32
 231  year_fraction_relstart            3276 non-null   float32
 232  age_when_met                      3341 non-null   float32
 233  time_from_met_to_rel              3263 non-null   float32
 234  year_fraction_first_cohab         2630 non-null   float32
 235  time_from_rel_to_cohab            2578 non-null   float32
 236  hcm2017q24_R_cowork               3295 non-null   category
 237  hcm2017q24_R_friend               3295 non-null   category
 238  hcm2017q24_R_family               3295 non-null   category
 239  hcm2017q24_R_sig_other            3295 non-null   category
 240  hcm2017q24_R_neighbor             3295 non-null   category
 241  hcm2017q24_P_cowork               3295 non-null   category
 242  hcm2017q24_P_friend               3295 non-null   category
 243  hcm2017q24_P_family               3295 non-null   category
 244  hcm2017q24_P_sig_other            3295 non-null   category
 245  hcm2017q24_P_neighbor             3295 non-null   category
 246  hcm2017q24_btwn_I_cowork          3295 non-null   category
 247  hcm2017q24_btwn_I_friend          3295 non-null   category
 248  hcm2017q24_btwn_I_family          3295 non-null   category
 249  hcm2017q24_btwn_I_sig_other       3295 non-null   category
 250  hcm2017q24_btwn_I_neighbor        3295 non-null   category
 251  hcm2017q24_school                 3295 non-null   category
 252  hcm2017q24_college                3295 non-null   category
 253  hcm2017q24_mil                    3295 non-null   category
 254  hcm2017q24_church                 3295 non-null   category
 255  hcm2017q24_vol_org                3295 non-null   category
 256  hcm2017q24_customer               3295 non-null   category
 257  hcm2017q24_bar_restaurant         3295 non-null   category
 258  hcm2017q24_party                  3295 non-null   category
 259  hcm2017q24_internet_other         3295 non-null   category
 260  hcm2017q24_internet_dating        3295 non-null   category
 261  hcm2017q24_internet_soc_network   3295 non-null   category
 262  hcm2017q24_internet_game          3295 non-null   category
 263  hcm2017q24_internet_chat          3295 non-null   category
 264  hcm2017q24_internet_org           3295 non-null   category
 265  hcm2017q24_public                 3295 non-null   category
 266  hcm2017q24_blind_date             3295 non-null   category
 267  hcm2017q24_vacation               3295 non-null   category
 268  hcm2017q24_single_serve_nonint    3295 non-null   category
 269  hcm2017q24_business_trip          3295 non-null   category
 270  hcm2017q24_work_neighbors         3295 non-null   category
 271  hcm2017q24_met_online             3394 non-null   category
 272  hcm2017_q24_length                3394 non-null   float32
 273  hcm2017q24_summary_all_codes      3295 non-null   float64
 274  w6_relationship_quality           2847 non-null   category
 275  hcm2017q24_met_through_family     3295 non-null   category
 276  hcm2017q24_met_through_friend     3295 non-null   category
 277  hcm2017q24_met_through_as_nghbrs  3295 non-null   category
 278  hcm2017q24_met_as_through_cowork  3295 non-null   category
 279  w6_subject_race                   3494 non-null   category
 280  interracial_5cat                  3365 non-null   category
 281  partner_mother_yrsed              3323 non-null   float32
 282  subject_mother_yrsed              3378 non-null   float32
 283  partner_yrsed                     3383 non-null   float32
 284  subject_yrsed                     3510 non-null   float32
dtypes: category(243), float32(20), float64(18), int16(2), int32(1), int8(1)
memory usage: 1.7 MB

# Select Specific Features to Keep

- Some features are redundant.
    - For example, some are just recodings of each other.
- Some features contain more of the same information.
    - Q4 and w6_q4 contain subject's partner's gender, but only w6_q4 contains gender for couples that are still together AND couples that are broken up.
    - w6_q4 will be selected to use. Q4 will not be used.
- Some features I'm uncertain about whether or not they will be useful, so I will leave them commented out.

In [4]:
features = [
    
    "CASEID_NEW", # ID
    "w6_sex_frequency", # sexFrequency
    "ppp20072", # attendReligiousServiceFreq
    "pphhsize", # household size
    "pphouse", # type of house
    "ppincimp", # household income
    "ppmsacat", # metro area
    "pprent", # own, rent, other
    "ppwork", # employment status
    "w6_q15a1_truncated", # subject grew up in US?
    "w6_q15a4_truncated", # subject's living country when met partner
    "w6_q16", # how many relatives subject sees per month?
    "w6_q17", # how many times has subject been married?
    "w6_q23", # Who earned more (in 2016 or when last together)
    "interracial_5cat", # based on w6_subject_race and w6_q6b
    "w6_q32", # did you use an Internet service to meet partner?
    "age_when_met", # age when met in years,=ppage-(2017- w6_q21a_year)
    "w6_q4", # partner gender
    "partyid7", # subject's political party
    "w6_q12", # partner's political party
    "ppgender", # subject gender
    "S1", # isMarried
    "ppage", # subject age
    "w6_q9", # partner's age in 2017
    "subject_yrsed", # RECODE of ppeduc (Education (Highest Degree Received))
    "partner_yrsed", # RECODE of w6_q10 (partner's educational attainment)
    "subject_mother_yrsed", # RECODE of w6_q14 (Subject's mother's educational attainment)
    "partner_mother_yrsed", # RECODE of w6_q11 (partner's mother's Education)
    "w6_subject_race", # based on single races Race_x
    "w6_q6b", # partner's race
    "PPREG4", # region
    "w6_same_sex_couple_gender", # same sex couple specific (0=straight, 1=gay, 2=lesbian)
    "w6_attraction", # what gender(s) subject attracted to?
    "w6_q19", # couple living together?
    "w6_q34", # how would you describe the quality of your relationship with partner?
    "w6_identity_all", # subject sexual identity
    "PPT01", # household member age (number of babies in household ages 0-1)
    "PPT25", # household member age (number of toddlers in household ages 2-5)
    "PPT612", # household member age (number of children in household ages 6-12)
    "PPT1317", # household member age (number of teens in household ages 13-17)
    "PPT18OV", # household member age (number of adults in household ages 18+)
    
    # Year/Month of Relationship Stages  ---------------------------- 
    
#     "w6_q21a_year", # year subject first met partner
#     "w6_q21a_month", # month subject first met partner
#     "w6_q21b_year", # year subject began romantic relationship w partner
#     "w6_q21b_month", # month subject began romantic relationship w partner
#     "w6_q21c_year", # year subject first lived with partner
#     "w6_q21c_month", # month subject first lived with partner
#     "w6_q21d_year", # year subject married partner
#     "w6_q21d_month", # month subject married partner
#     "w6_q21e_year", # year of breakup
#     "w6_q21e_month", # month of breakup
#     "w6_q21f_year", # year partner died
#     "w6_q21f_month", # month partner died
    
    # (Fractions) Year/Month of Relationship Stages ---------------
    
    "year_fraction_met", # w6_q21a_year+((w6_q21a_month-0.5)/12)
    "year_fraction_relstart", # w6_q21b_year+((w6_q21b_month-0.5)/12)
    "time_from_met_to_rel", # year_fraction_relstart-year_fraction_met
    "year_fraction_first_cohab", # w6_q21c_year+((w6_q21c_month-0.5)/12)
    "time_from_rel_to_cohab", # year_fraction_first_cohab-year_fraction_relstart, neg reset to zero
    
    
    # Met in person -----------------------------------------------
    
#     "w6_q25", # did subject and partner attend same H.S.
#     "w6_q26", # did subject and partner attend same college
#     "w6_q27", # did subject and partner grow up in same city or town
#     "w6_q28", # did subject's parents know partner's parents before subject knew partner?
#     "w6_friend_connect_1_all", # subject knew partner's friends before meeting partner
#     "w6_friend_connect_2_all", # partner knew subjects friends before meeting subject
#     "w6_friend_connect_3_all", # subject's friends knew partner's friends before subject and partner met
#     "w6_friend_connect_4_all", # no prior connection between subject's friends and partner's friends
    
#     "hcm2017q24_R_cowork", # Respondent's coworker: indermediary or partner
#     "hcm2017q24_R_friend", # Respondent's friend: intermediary
#     "hcm2017q24_R_family", # Respondent's family: intermediary
#     "hcm2017q24_R_sig_other", # Respondent's (current or past) Significant Other: Intermediary
#     "hcm2017q24_R_neighbor", # Respondent's residential neighbor: intermediary or Partner
#     "hcm2017q24_P_cowork", # Partner's coworker: Intermediary or Respondent
#     "hcm2017q24_P_friend", # Partner's Friend: Intermediary
#     "hcm2017q24_P_family", # Partner's Family: Intermediary
#     "hcm2017q24_P_sig_other", # Partner's (current or past) Significant Other: Intermediary
#     "hcm2017q24_P_neighbor", # Partner's residential neighbor: Intermediary or Respondent
    
    "hcm2017q24_met_through_family", # 1 if R_family or P_family =1
    "hcm2017q24_met_through_friend", # 1 if R_friend or P_friend=1
    "hcm2017q24_met_through_as_nghbrs", # 1 if R_neighbor or P_neighbor=1
    "hcm2017q24_met_as_through_cowork", # 1 if R_cowork or P_cowork=1

    "hcm2017q24_school", # met in primary or secondary school
    "hcm2017q24_college", # met in college
    "hcm2017q24_mil", # met during military service
    "hcm2017q24_church", # met in or through church or religious organization
    "hcm2017q24_vol_org", # met through voluntary organization (non-church)
    "hcm2017q24_customer", # customer-client relationship
    "hcm2017q24_bar_restaurant", # restaurant, or othe public social gathering place
    "hcm2017q24_party", # private party
    
    "hcm2017q24_public", # met in public place
    "hcm2017q24_blind_date", # met on blind date
    "hcm2017q24_vacation", # met while on vacation
    "hcm2017q24_single_serve_nonint", # non internet single service
    "hcm2017q24_business_trip", # met while on business trip
    "hcm2017q24_work_neighbors", # met as work neighbors
    
    # Met online / dating app -----------------------------------------------
    
    "hcm2017q24_internet_other", # Internet, not otherwise classified
    "hcm2017q24_internet_dating", # met through Internet dating or phone app
    "hcm2017q24_internet_soc_network", # met through internet social networking
    
    "hcm2017q24_internet_game", # met through online gaming
    "hcm2017q24_internet_chat", # met through Internet chat
    "hcm2017q24_internet_org", # met through Internet site not mainly dedicated to dating

    "hcm2017q24_met_online", # met online, all kinds


    # to be filtered ---------------------
    
    "qflag", # DOV: Qualification Flag - Remove 2
    "speed_flag", # Respondents who completed survey in under 2 min - Remove under 2
    "S3", # Ever had a boyfriend or a girlfriend - Remove "No"
    "w6_took_the_survey", # Whether subject took the survey or was excluded
    "partnership_status", # Filter out 4 (never had) married, parner, ex
    
    
    # to be recoded ----------------------
    
    "ppeduc", # subject education
    "w6_q10", # partner's education 
    "w6_q11", # partner's mother's education
    "w6_q14", # subjects's mother's education
    
    "ppethm", # subject is Hispanic -- convert to binary

]

df = imported_data[features].copy()

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3510 entries, 0 to 3509
Data columns (total 81 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   CASEID_NEW                        3510 non-null   int32
 1   w6_sex_frequency                  2856 non-null   category
 2   ppp20072                          3394 non-null   category
 3   pphhsize                          3510 non-null   category
 4   pphouse                           3510 non-null   category
 5   ppincimp                          3510 non-null   category
 6   ppmsacat                          3510 non-null   category
 7   pprent                            3510 non-null   category
 8   ppwork                            3510 non-null   category
 9   w6_q15a1_truncated                3394 non-null   category
 10  w6_q15a4_truncated                3394 non-null   category
 11  w6_q16                            3367 non-null   float64
 12  w6_q17                            3385 non-null   float64
 13  w6_q23                            3394 non-null   category
 14  interracial_5cat                  3365 non-null   category
 15  w6_q32                            3394 non-null   category
 16  age_when_met                      3341 non-null   float32
 17  w6_q4                             3394 non-null   category
 18  partyid7                          3394 non-null   category
 19  w6_q12                            3394 non-null   category
 20  ppgender                          3510 non-null   category
 21  S1                                3510 non-null   category
 22  ppage                             3510 non-null   category
 23  w6_q9                             3374 non-null   float64
 24  subject_yrsed                     3510 non-null   float32
 25  partner_yrsed                     3383 non-null   float32
 26  subject_mother_yrsed              3378 non-null   float32
 27  partner_mother_yrsed              3323 non-null   float32
 28  w6_subject_race                   3494 non-null   category
 29  w6_q6b                            3394 non-null   category
 30  PPREG4                            3510 non-null   category
 31  w6_same_sex_couple_gender         3394 non-null   category
 32  w6_attraction                     3381 non-null   category
 33  w6_q19                            2856 non-null   category
 34  w6_q34                            2856 non-null   category
 35  w6_identity_all                   3394 non-null   category
 36  PPT01                             3510 non-null   category
 37  PPT25                             3510 non-null   category
 38  PPT612                            3510 non-null   category
 39  PPT1317                           3510 non-null   category
 40  PPT18OV                           3510 non-null   category
 41  year_fraction_met                 3341 non-null   float32
 42  year_fraction_relstart            3276 non-null   float32
 43  time_from_met_to_rel              3263 non-null   float32
 44  year_fraction_first_cohab         2630 non-null   float32
 45  time_from_rel_to_cohab            2578 non-null   float32
 46  hcm2017q24_met_through_family     3295 non-null   category
 47  hcm2017q24_met_through_friend     3295 non-null   category
 48  hcm2017q24_met_through_as_nghbrs  3295 non-null   category
 49  hcm2017q24_met_as_through_cowork  3295 non-null   category
 50  hcm2017q24_school                 3295 non-null   category
 51  hcm2017q24_college                3295 non-null   category
 52  hcm2017q24_mil                    3295 non-null   category
 53  hcm2017q24_church                 3295 non-null   category
 54  hcm2017q24_vol_org                3295 non-null   category
 55  hcm2017q24_customer               3295 non-null   category
 56  hcm2017q24_bar_restaurant         3295 non-null   category
 57  hcm2017q24_party                  3295 non-null   category
 58  hcm2017q24_public                 3295 non-null   category
 59  hcm2017q24_blind_date             3295 non-null   category
 60  hcm2017q24_vacation               3295 non-null   category
 61  hcm2017q24_single_serve_nonint    3295 non-null   category
 62  hcm2017q24_business_trip          3295 non-null   category
 63  hcm2017q24_work_neighbors         3295 non-null   category
 64  hcm2017q24_internet_other         3295 non-null   category
 65  hcm2017q24_internet_dating        3295 non-null   category
 66  hcm2017q24_internet_soc_network   3295 non-null   category
 67  hcm2017q24_internet_game          3295 non-null   category
 68  hcm2017q24_internet_chat          3295 non-null   category
 69  hcm2017q24_internet_org           3295 non-null   category
 70  hcm2017q24_met_online             3394 non-null   category
 71  qflag                             3510 non-null   category
 72  speed_flag                        3510 non-null   category
 73  S3                                648 non-null    category
 74  w6_took_the_survey                3510 non-null   category
 75  partnership_status                3510 non-null   category
 76  ppeduc                            3510 non-null   category
 77  w6_q10                            3394 non-null   category
 78  w6_q11                            3394 non-null   category
 79  w6_q14                            3394 non-null   category
 80  ppethm                            3510 non-null   category
dtypes: category(67), float32(10), float64(3), int32(1)
memory usage: 506.5 KB

# Filtering

Removing respondents who:
- weren't qualified for the survey
- did the survey questionably quickly
- have never had a partner
- were excluded from survey

In [5]:
isQualified = df["qflag"] == "Qualified"
overTwoMin = df["speed_flag"] == "Completed survey in over 2 minutes"
hasOrHadPartner = df["S3"] != "No"
tookTheSurvey = df["w6_took_the_survey"] == "took the survey"

print("Original dataset had", len(df), "rows.")

df_filtered = df[isQualified & overTwoMin & hasOrHadPartner & tookTheSurvey].copy()

print("Filtered dataset has", len(df_filtered), "rows.")

Original dataset had 3510 rows.
Filtered dataset has 3391 rows.

# Renamed Dataframe

- Creating a copy of the df_filtered to rename columns.

In [6]:
# make a copy of df dataframe

df_renamed = df_filtered.copy()

cols_to_keepOut = ["qflag", 
                   "speed_flag", 
                   "S3", 
                   "w6_took_the_survey", 
                   "partnership_status"]

df_renamed.drop(cols_to_keepOut, axis=1, inplace=True)

cols_to_rename = {
    "CASEID_NEW": "ID",
    "w6_sex_frequency": "sexFrequency",
    "ppp20072": "attendReligiousServiceFreq",
    "pphhsize": "householdSize",
    "pphouse": "houseType",
    "ppincimp": "householdIncome",
    "ppmsacat": "isMetroArea",
    "pprent": "ownHouseRentOther", # own, rent, other
    "ppwork": "employmentStatus", # employment status
    "w6_q15a1_truncated": "subjectGrewUpInUS", # subject grew up in US?
    "w6_q15a4_truncated": "subjectCountryWhenMetPartner", # subject's living country when met partner
    "w6_q16": "numRelativesSeePerMonth", # how many relatives subject sees per month?
    "w6_q17": "numOfTimesMarried", # how many times has subject been married?
    "w6_q23": "whoEarnedMore", # Who earned more (in 2016 or when last together)
    "interracial_5cat": "interracial", # based on w6_subject_race and w6_q6b
    "w6_q32": "usedAnInternetServiceToMeet", # did you use an Internet service to meet partner?
    "age_when_met": "ageWhenMet", # age when met in years,=ppage-(2017- w6_q21a_year)
    "w6_q4": "partnerGender", # partner gender
    "partyid7": "subjectPoliticalParty", # subject's political party
    "w6_q12": "partnerPoliticalParty", # partner's political party
    "ppgender": "subjectGender", # subject gender
    "S1": "isMarried", # isMarried
    "ppage": "subjectAge", # subject age
    "w6_q9": "partnerAge", # partner's age in 2017
    "subject_yrsed": "subjectEduc_years", # RECODE of ppeduc (Education (Highest Degree Received))
    "partner_yrsed": "partnerEduc_years", # RECODE of w6_q10 (partner's educational attainment)
    "subject_mother_yrsed": "subjectMotherEduc_years", # RECODE of w6_q14 (Subject's mother's educational attainment)
    "partner_mother_yrsed": "partnerMotherEduc_years", # RECODE of w6_q11 (partner's mother's Education)
    "w6_subject_race": "subjectRace", # based on single races Race_x
    "w6_q6b": "partnerRace", # partner's race
    "PPREG4": "region", # region
    "w6_same_sex_couple_gender": "straightGayLesbian", # same sex couple specific (0=straight, 1=gay, 2=lesbian)
    "w6_attraction": "genderSubjectAttractedTo", 
        # what gender(s) subject attracted to? (opposite gender, opposite but, both, same but, same gender)
    "w6_q19": "isLivingTogether", # couple living together?
    "w6_q34": "relationshipQuality", # how would you describe the quality of your relationship with partner?
    "w6_identity_all": "subjectSexualIdentity", # subject sexual identity
    "PPT01": "numOfHouseMembersAges0to1", # household member age (number of babies in household ages 0-1)
    "PPT25": "numOfHouseMembersAges2to5", # household member age (number of toddlers in household ages 2-5)
    "PPT612": "numOfHouseMembersAges6to12", # household member age (number of children in household ages 6-12)
    "PPT1317": "numOfHouseMembersAges13to17", # household member age (number of teens in household ages 13-17)
    "PPT18OV": "numOfHouseMembersAges18toOver", # household member age (number of adults in household ages 18+)
    
    # (Fractions) Year/Month of Relationship Stages ---------------
    
    "year_fraction_met": "met_YearFraction", # w6_q21a_year+((w6_q21a_month-0.5)/12)
    "year_fraction_relstart": "shipStart_YearFraction", # w6_q21b_year+((w6_q21b_month-0.5)/12)
    "time_from_met_to_rel": "met_to_shipStart_diff", # year_fraction_relstart-year_fraction_met
    "year_fraction_first_cohab": "moveIn_YearFraction", # w6_q21c_year+((w6_q21c_month-0.5)/12)
    "time_from_rel_to_cohab": "shipStart_to_moveIn_YearFraction", # year_fraction_first_cohab-year_fraction_relstart, neg reset to zero
    
    
    # met in person (specific) -----------------------------------------------------
    
    "hcm2017q24_met_through_family": "metThru_family", # 1 if R_family or P_family =1
    "hcm2017q24_met_through_friend": "metThru_friend", # 1 if R_friend or P_friend=1
    "hcm2017q24_met_through_as_nghbrs": "metThru_orAs_neighbors", # 1 if R_neighbor or P_neighbor=1
    "hcm2017q24_met_as_through_cowork": "metAs_coworkers", # 1 if R_cowork or P_cowork=1
    
    "hcm2017q24_school": "metIn_school", # met in primary or secondary school
    "hcm2017q24_college": "metIn_college", # met in college
    "hcm2017q24_mil": "metIn_military", # met during military service
    "hcm2017q24_church": "metIn_church", # met in or through church or religious organization
    "hcm2017q24_vol_org": "metIn_voluntaryOrg", # met through voluntary organization (non-church)
    "hcm2017q24_customer": "metAs_customerAndClient", # customer-client relationship
    "hcm2017q24_bar_restaurant": "metIn_restaurantOrBar", # restaurant, or other public social gathering place
    "hcm2017q24_party": "metIn_privateParty", # private party
    
    "hcm2017q24_public": "metIn_public", # met in public place
    "hcm2017q24_blind_date": "metOn_blindDate", # met on blind date
    "hcm2017q24_vacation": "metOn_vacation", # met while on vacation
    "hcm2017q24_single_serve_nonint": "metThru_notInternetDatingService", # non internet single service
    "hcm2017q24_business_trip": "metOn_businessTrip", # met while on business trip
    "hcm2017q24_work_neighbors": "metAs_workNeighbors", # met as work neighbors
    
    
    # Met online / dating app -----------------------------------------------
    
    
    "hcm2017q24_internet_dating": "metOnline_datingSiteOrApp", # met through Internet dating or phone app
    "hcm2017q24_internet_soc_network": "metOnline_socialNetwork", # met through internet social networking
    
    "hcm2017q24_internet_game": "metOnline_gaming", # met through online gaming
    "hcm2017q24_internet_chat": "metOnline_chat", # met through Internet chat
    "hcm2017q24_internet_org": "metOnline_nonDatingSite", # met through Internet site not mainly dedicated to dating
    
    "hcm2017q24_internet_other": "metOnline_other", # Internet, not otherwise classified

    "hcm2017q24_met_online": "metOnline_all", # met online, all kinds


}

    
df_renamed.rename(columns=cols_to_rename, inplace=True)

df_renamed.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3391 entries, 0 to 3509
Data columns (total 76 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                3391 non-null   int32
 1   sexFrequency                      2853 non-null   category
 2   attendReligiousServiceFreq        3391 non-null   category
 3   householdSize                     3391 non-null   category
 4   houseType                         3391 non-null   category
 5   householdIncome                   3391 non-null   category
 6   isMetroArea                       3391 non-null   category
 7   ownHouseRentOther                 3391 non-null   category
 8   employmentStatus                  3391 non-null   category
 9   subjectGrewUpInUS                 3391 non-null   category
 10  subjectCountryWhenMetPartner      3391 non-null   category
 11  numRelativesSeePerMonth           3365 non-null   float64
 12  numOfTimesMarried                 3383 non-null   float64
 13  whoEarnedMore                     3391 non-null   category
 14  interracial                       3362 non-null   category
 15  usedAnInternetServiceToMeet       3391 non-null   category
 16  ageWhenMet                        3339 non-null   float32
 17  partnerGender                     3391 non-null   category
 18  subjectPoliticalParty             3391 non-null   category
 19  partnerPoliticalParty             3391 non-null   category
 20  subjectGender                     3391 non-null   category
 21  isMarried                         3391 non-null   category
 22  subjectAge                        3391 non-null   category
 23  partnerAge                        3371 non-null   float64
 24  subjectEduc_years                 3391 non-null   float32
 25  partnerEduc_years                 3380 non-null   float32
 26  subjectMotherEduc_years           3375 non-null   float32
 27  partnerMotherEduc_years           3320 non-null   float32
 28  subjectRace                       3376 non-null   category
 29  partnerRace                       3391 non-null   category
 30  region                            3391 non-null   category
 31  straightGayLesbian                3391 non-null   category
 32  genderSubjectAttractedTo          3379 non-null   category
 33  isLivingTogether                  2853 non-null   category
 34  relationshipQuality               2853 non-null   category
 35  subjectSexualIdentity             3391 non-null   category
 36  numOfHouseMembersAges0to1         3391 non-null   category
 37  numOfHouseMembersAges2to5         3391 non-null   category
 38  numOfHouseMembersAges6to12        3391 non-null   category
 39  numOfHouseMembersAges13to17       3391 non-null   category
 40  numOfHouseMembersAges18toOver     3391 non-null   category
 41  met_YearFraction                  3339 non-null   float32
 42  shipStart_YearFraction            3274 non-null   float32
 43  met_to_shipStart_diff             3261 non-null   float32
 44  moveIn_YearFraction               2628 non-null   float32
 45  shipStart_to_moveIn_YearFraction  2576 non-null   float32
 46  metThru_family                    3293 non-null   category
 47  metThru_friend                    3293 non-null   category
 48  metThru_orAs_neighbors            3293 non-null   category
 49  metAs_coworkers                   3293 non-null   category
 50  metIn_school                      3293 non-null   category
 51  metIn_college                     3293 non-null   category
 52  metIn_military                    3293 non-null   category
 53  metIn_church                      3293 non-null   category
 54  metIn_voluntaryOrg                3293 non-null   category
 55  metAs_customerAndClient           3293 non-null   category
 56  metIn_restaurantOrBar             3293 non-null   category
 57  metIn_privateParty                3293 non-null   category
 58  metIn_public                      3293 non-null   category
 59  metOn_blindDate                   3293 non-null   category
 60  metOn_vacation                    3293 non-null   category
 61  metThru_notInternetDatingService  3293 non-null   category
 62  metOn_businessTrip                3293 non-null   category
 63  metAs_workNeighbors               3293 non-null   category
 64  metOnline_other                   3293 non-null   category
 65  metOnline_datingSiteOrApp         3293 non-null   category
 66  metOnline_socialNetwork           3293 non-null   category
 67  metOnline_gaming                  3293 non-null   category
 68  metOnline_chat                    3293 non-null   category
 69  metOnline_nonDatingSite           3293 non-null   category
 70  metOnline_all                     3391 non-null   category
 71  ppeduc                            3391 non-null   category
 72  w6_q10                            3391 non-null   category
 73  w6_q11                            3391 non-null   category
 74  w6_q14                            3391 non-null   category
 75  ppethm                            3391 non-null   category
dtypes: category(62), float32(10), float64(3), int32(1)
memory usage: 472.7 KB

# Recode categorical education features

In [7]:
print(list(df_renamed["ppeduc"].unique()))
print("\n")
print(list(df_renamed["w6_q10"].unique()))

['Associate degree', 'Masters degree', '12th grade NO DIPLOMA', 'Bachelors degree', 'HIGH SCHOOL GRADUATE - high school DIPLOMA or the equivalent (GED)', 'Professional or Doctorate degree', 'Some college, no degree', '9th grade', '10th grade', '11th grade', '7th or 8th grade', '5th or 6th grade', '1st, 2nd, 3rd, or 4th grade', 'No formal education']


['HS graduate or GED', 'Master\x92s degree', 'Associate degree', 'Bachelor\x92s degree', 'Some college, no degree', 'Professional or Doctorate degree', '12th grade no diploma', '11th grade', '10th grade', '7th or 8th grade', 'No formal education', '9th grade', 'Refused', '5th or 6th grade', '1st-4th grade']

In [8]:
education_recodings = {"No formal education": "1-Less than high school",
                       "1st-4th grade": "1-Less than high school",
                       "1st, 2nd, 3rd, or 4th grade": "1-Less than high school",
                       "5th or 6th grade": "1-Less than high school",
                       "7th or 8th grade": "1-Less than high school",
                       "9th grade": "1-Less than high school",
                       "10th grade": "1-Less than high school",
                       "11th grade": "1-Less than high school",
                       "12th grade no diploma": "1-Less than high school",
                       "12th grade NO DIPLOMA": "1-Less than high school",
                       "HS graduate or GED": "2-High school",
                       "HIGH SCHOOL GRADUATE - high school DIPLOMA or the equivalent (GED)": "2-High school",
                       "Some college, no degree": "3-Some college",
                       "Associate degree": "3-Some college",
                       "Bachelors degree": "4-Bachelor's degree",
                       "Bachelor\x92s degree": "4-Bachelor's degree",
                       "Master\x92s degree": "5-Professional or Graduate degree",
                       "Masters degree": "5-Professional or Graduate degree",
                       "Professional or Doctorate degree": "5-Professional or Graduate degree"}


df_renamed["ppeduc"].replace(education_recodings, inplace=True) # subject's education
df_renamed["w6_q10"].replace(education_recodings, inplace=True) # partner's education
df_renamed["w6_q14"].replace(education_recodings, inplace=True) # subjects's mother's education
df_renamed["w6_q11"].replace(education_recodings, inplace=True) # partner's mother's education

In [9]:
print(list(df_renamed["ppeduc"].unique()))
print("\n")
print(list(df_renamed["w6_q10"].unique()))

['3-Some college', '5-Professional or Graduate degree', '1-Less than high school', "4-Bachelor's degree", '2-High school']


['2-High school', '5-Professional or Graduate degree', '3-Some college', "4-Bachelor's degree", '1-Less than high school', 'Refused']

### Rename education columns

In [10]:

cols_to_rename = {
    "ppeduc": "subjectEduc_cat",
    "w6_q10": "partnerEduc_cat",
    "w6_q14": "subjectMotherEduc_cat",
    "w6_q11": "partnerMotherEduc_cat"
}

    
df_renamed.rename(columns=cols_to_rename, inplace=True)

df_renamed.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3391 entries, 0 to 3509
Data columns (total 76 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                3391 non-null   int32
 1   sexFrequency                      2853 non-null   category
 2   attendReligiousServiceFreq        3391 non-null   category
 3   householdSize                     3391 non-null   category
 4   houseType                         3391 non-null   category
 5   householdIncome                   3391 non-null   category
 6   isMetroArea                       3391 non-null   category
 7   ownHouseRentOther                 3391 non-null   category
 8   employmentStatus                  3391 non-null   category
 9   subjectGrewUpInUS                 3391 non-null   category
 10  subjectCountryWhenMetPartner      3391 non-null   category
 11  numRelativesSeePerMonth           3365 non-null   float64
 12  numOfTimesMarried                 3383 non-null   float64
 13  whoEarnedMore                     3391 non-null   category
 14  interracial                       3362 non-null   category
 15  usedAnInternetServiceToMeet       3391 non-null   category
 16  ageWhenMet                        3339 non-null   float32
 17  partnerGender                     3391 non-null   category
 18  subjectPoliticalParty             3391 non-null   category
 19  partnerPoliticalParty             3391 non-null   category
 20  subjectGender                     3391 non-null   category
 21  isMarried                         3391 non-null   category
 22  subjectAge                        3391 non-null   category
 23  partnerAge                        3371 non-null   float64
 24  subjectEduc_years                 3391 non-null   float32
 25  partnerEduc_years                 3380 non-null   float32
 26  subjectMotherEduc_years           3375 non-null   float32
 27  partnerMotherEduc_years           3320 non-null   float32
 28  subjectRace                       3376 non-null   category
 29  partnerRace                       3391 non-null   category
 30  region                            3391 non-null   category
 31  straightGayLesbian                3391 non-null   category
 32  genderSubjectAttractedTo          3379 non-null   category
 33  isLivingTogether                  2853 non-null   category
 34  relationshipQuality               2853 non-null   category
 35  subjectSexualIdentity             3391 non-null   category
 36  numOfHouseMembersAges0to1         3391 non-null   category
 37  numOfHouseMembersAges2to5         3391 non-null   category
 38  numOfHouseMembersAges6to12        3391 non-null   category
 39  numOfHouseMembersAges13to17       3391 non-null   category
 40  numOfHouseMembersAges18toOver     3391 non-null   category
 41  met_YearFraction                  3339 non-null   float32
 42  shipStart_YearFraction            3274 non-null   float32
 43  met_to_shipStart_diff             3261 non-null   float32
 44  moveIn_YearFraction               2628 non-null   float32
 45  shipStart_to_moveIn_YearFraction  2576 non-null   float32
 46  metThru_family                    3293 non-null   category
 47  metThru_friend                    3293 non-null   category
 48  metThru_orAs_neighbors            3293 non-null   category
 49  metAs_coworkers                   3293 non-null   category
 50  metIn_school                      3293 non-null   category
 51  metIn_college                     3293 non-null   category
 52  metIn_military                    3293 non-null   category
 53  metIn_church                      3293 non-null   category
 54  metIn_voluntaryOrg                3293 non-null   category
 55  metAs_customerAndClient           3293 non-null   category
 56  metIn_restaurantOrBar             3293 non-null   category
 57  metIn_privateParty                3293 non-null   category
 58  metIn_public                      3293 non-null   category
 59  metOn_blindDate                   3293 non-null   category
 60  metOn_vacation                    3293 non-null   category
 61  metThru_notInternetDatingService  3293 non-null   category
 62  metOn_businessTrip                3293 non-null   category
 63  metAs_workNeighbors               3293 non-null   category
 64  metOnline_other                   3293 non-null   category
 65  metOnline_datingSiteOrApp         3293 non-null   category
 66  metOnline_socialNetwork           3293 non-null   category
 67  metOnline_gaming                  3293 non-null   category
 68  metOnline_chat                    3293 non-null   category
 69  metOnline_nonDatingSite           3293 non-null   category
 70  metOnline_all                     3391 non-null   category
 71  subjectEduc_cat                   3391 non-null   category
 72  partnerEduc_cat                   3391 non-null   category
 73  partnerMotherEduc_cat             3391 non-null   category
 74  subjectMotherEduc_cat             3391 non-null   category
 75  ppethm                            3391 non-null   category
dtypes: category(62), float32(10), float64(3), int32(1)
memory usage: 470.9 KB

# Recode and create binary isHispanic feature

In [11]:
print(list(df_renamed["ppethm"].unique()))

['White, Non-Hispanic', 'Hispanic', 'Black, Non-Hispanic', '2+ Races, Non-Hispanic', 'Other, Non-Hispanic']

In [12]:
df_renamed["isHispanic"] = df_renamed["ppethm"] == "Hispanic"

df_renamed.drop("ppethm", axis=1, inplace=True)

df_renamed["isHispanic"].unique()

array([False,  True])

In [13]:
df_renamed.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3391 entries, 0 to 3509
Data columns (total 76 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   ID                                3391 non-null   int32
 1   sexFrequency                      2853 non-null   category
 2   attendReligiousServiceFreq        3391 non-null   category
 3   householdSize                     3391 non-null   category
 4   houseType                         3391 non-null   category
 5   householdIncome                   3391 non-null   category
 6   isMetroArea                       3391 non-null   category
 7   ownHouseRentOther                 3391 non-null   category
 8   employmentStatus                  3391 non-null   category
 9   subjectGrewUpInUS                 3391 non-null   category
 10  subjectCountryWhenMetPartner      3391 non-null   category
 11  numRelativesSeePerMonth           3365 non-null   float64
 12  numOfTimesMarried                 3383 non-null   float64
 13  whoEarnedMore                     3391 non-null   category
 14  interracial                       3362 non-null   category
 15  usedAnInternetServiceToMeet       3391 non-null   category
 16  ageWhenMet                        3339 non-null   float32
 17  partnerGender                     3391 non-null   category
 18  subjectPoliticalParty             3391 non-null   category
 19  partnerPoliticalParty             3391 non-null   category
 20  subjectGender                     3391 non-null   category
 21  isMarried                         3391 non-null   category
 22  subjectAge                        3391 non-null   category
 23  partnerAge                        3371 non-null   float64
 24  subjectEduc_years                 3391 non-null   float32
 25  partnerEduc_years                 3380 non-null   float32
 26  subjectMotherEduc_years           3375 non-null   float32
 27  partnerMotherEduc_years           3320 non-null   float32
 28  subjectRace                       3376 non-null   category
 29  partnerRace                       3391 non-null   category
 30  region                            3391 non-null   category
 31  straightGayLesbian                3391 non-null   category
 32  genderSubjectAttractedTo          3379 non-null   category
 33  isLivingTogether                  2853 non-null   category
 34  relationshipQuality               2853 non-null   category
 35  subjectSexualIdentity             3391 non-null   category
 36  numOfHouseMembersAges0to1         3391 non-null   category
 37  numOfHouseMembersAges2to5         3391 non-null   category
 38  numOfHouseMembersAges6to12        3391 non-null   category
 39  numOfHouseMembersAges13to17       3391 non-null   category
 40  numOfHouseMembersAges18toOver     3391 non-null   category
 41  met_YearFraction                  3339 non-null   float32
 42  shipStart_YearFraction            3274 non-null   float32
 43  met_to_shipStart_diff             3261 non-null   float32
 44  moveIn_YearFraction               2628 non-null   float32
 45  shipStart_to_moveIn_YearFraction  2576 non-null   float32
 46  metThru_family                    3293 non-null   category
 47  metThru_friend                    3293 non-null   category
 48  metThru_orAs_neighbors            3293 non-null   category
 49  metAs_coworkers                   3293 non-null   category
 50  metIn_school                      3293 non-null   category
 51  metIn_college                     3293 non-null   category
 52  metIn_military                    3293 non-null   category
 53  metIn_church                      3293 non-null   category
 54  metIn_voluntaryOrg                3293 non-null   category
 55  metAs_customerAndClient           3293 non-null   category
 56  metIn_restaurantOrBar             3293 non-null   category
 57  metIn_privateParty                3293 non-null   category
 58  metIn_public                      3293 non-null   category
 59  metOn_blindDate                   3293 non-null   category
 60  metOn_vacation                    3293 non-null   category
 61  metThru_notInternetDatingService  3293 non-null   category
 62  metOn_businessTrip                3293 non-null   category
 63  metAs_workNeighbors               3293 non-null   category
 64  metOnline_other                   3293 non-null   category
 65  metOnline_datingSiteOrApp         3293 non-null   category
 66  metOnline_socialNetwork           3293 non-null   category
 67  metOnline_gaming                  3293 non-null   category
 68  metOnline_chat                    3293 non-null   category
 69  metOnline_nonDatingSite           3293 non-null   category
 70  metOnline_all                     3391 non-null   category
 71  subjectEduc_cat                   3391 non-null   category
 72  partnerEduc_cat                   3391 non-null   category
 73  partnerMotherEduc_cat             3391 non-null   category
 74  subjectMotherEduc_cat             3391 non-null   category
 75  isHispanic                        3391 non-null   bool
dtypes: bool(1), category(61), float32(10), float64(3), int32(1)
memory usage: 470.7 KB

In [16]:
# optionally alphbetize column names

df_renamed.sort_index(axis=1).head(3)

,ID,ageWhenMet,attendReligiousServiceFreq,employmentStatus,genderSubjectAttractedTo,houseType,householdIncome,householdSize,interracial,isHispanic,isLivingTogether,isMarried,isMetroArea,metAs_coworkers,metAs_customerAndClient,metAs_workNeighbors,metIn_church,metIn_college,metIn_military,metIn_privateParty,metIn_public,metIn_restaurantOrBar,metIn_school,metIn_voluntaryOrg,metOn_blindDate,metOn_businessTrip,metOn_vacation,metOnline_all,metOnline_chat,metOnline_datingSiteOrApp,metOnline_gaming,metOnline_nonDatingSite,metOnline_other,metOnline_socialNetwork,metThru_family,metThru_friend,metThru_notInternetDatingService,metThru_orAs_neighbors,met_YearFraction,met_to_shipStart_diff,moveIn_YearFraction,numOfHouseMembersAges0to1,numOfHouseMembersAges13to17,numOfHouseMembersAges18toOver,numOfHouseMembersAges2to5,numOfHouseMembersAges6to12,numOfTimesMarried,numRelativesSeePerMonth,ownHouseRentOther,partnerAge,partnerEduc_cat,partnerEduc_years,partnerGender,partnerMotherEduc_cat,partnerMotherEduc_years,partnerPoliticalParty,partnerRace,region,relationshipQuality,sexFrequency,shipStart_YearFraction,shipStart_to_moveIn_YearFraction,straightGayLesbian,subjectAge,subjectCountryWhenMetPartner,subjectEduc_cat,subjectEduc_years,subjectGender,subjectGrewUpInUS,subjectMotherEduc_cat,subjectMotherEduc_years,subjectPoliticalParty,subjectRace,subjectSexualIdentity,usedAnInternetServiceToMeet,whoEarnedMore
0,2014039,30.0,Never,Working - as a paid employee,sexually attracted to men and women equally,A one-family house detached from any other house,"$40,000 to $49,999",1,no,False,NaN,"No, I am not Married",Metro,no,no,no,no,no,no,no,no,no,no,no,no,no,no,yes,no,yes,no,no,no,no,no,no,no,no,2017.208374,0.000000,NaN,0,0,1,0,0,1.0,1.0,Owned or being bought by you or someone in you...,26.0,2-High school,12.0,[Partner Name] is Male,2-High school,12.0,Leans Republican,White,Northeast,NaN,NaN,2017.208374,NaN,gay male couple,30,United States,3-Some college,14.0,Male,United States,3-Some college,14.0,Leans Democrat,White,bisexual,"Yes, an Internet dating or matchmaking site (l...",I earned more
1,2019003,21.0,Never,Not working - other,sexually attracted only to opposite gender,A one-family house detached from any other house,"$150,000 to $174,999",4,no,False,Yes,"Yes, I am Married",Metro,yes,no,no,no,no,no,no,no,no,no,no,no,no,no,no,no,no,no,no,no,no,no,no,no,no,1983.375000,12.250000,1996.125000,0,2,2,0,0,1.0,1.0,Owned or being bought by you or someone in you...,52.0,5-Professional or Graduate degree,17.0,[Partner Name] is Male,2-High school,12.0,Leans Republican,White,Midwest,Excellent,Once a month or less,1995.625000,0.500000,hetero couple,55,United States,5-Professional or Graduate degree,17.0,Female,United States,4-Bachelor's degree,16.0,Not Strong Republican,White,heterosexual or straight,"No, I did NOT meet [Partner Name] through the ...",[Partner Name] earned more
2,2145527,36.0,Once or twice a month,Working - as a paid employee,sexually attracted only to opposite gender,A one-family house detached from any other house,"$200,000 to $249,999",5,no,False,Yes,"Yes, I am Married",Metro,no,no,no,no,no,no,no,no,yes,no,no,no,no,no,yes,no,no,no,no,yes,no,no,no,no,no,2006.041626,0.416748,2006.541626,0,0,2,1,2,1.0,0.0,Owned or being bought by you or someone in you...,45.0,3-Some college,14.0,[Partner Name] is Female,1-Less than high school,9.0,Leans Democrat,White,South,Good,2 to 3 times a month,2006.458374,0.083252,hetero couple,47,"Another country, please specify",5-Professional or Graduate degree,17.0,Male,"Another country, please specify",1-Less than high school,7.5,Leans Democrat,White,heterosexual or straight,"Yes, an Internet dating or matchmaking site (l...",I earned more